// ============================================================================
// Mock Data for LightPanel Premium UI
// Realistic infrastructure data for demo/development
// ============================================================================

import type {
  SystemStats,
  Application,
  Website,
  Domain,
  Subdomain,
  DatabaseExtended,
  SSLCertificate,
  Deployment,
  Backup,
  CronJob,
  LogEntry,
  Notification,
  ActivityEvent,
  FileItem,
  MonitoringDataPoint,
  EnvVariable,
  EmailDomain,
  Mailbox,
  EmailAlias,
  SpamSettings,
  DNSAuthRecord,
  MailMessage,
  MailLog,
  QueueItem,
} from '@/types';

// --- System Stats ---
export const mockStats: SystemStats = {
  cpu_usage: 23.4,
  mem_total_mb: 8192,
  mem_used_mb: 3276,
  mem_free_mb: 4916,
  mem_percent: 40.0,
  disk_total_gb: 256,
  disk_used_gb: 89,
  disk_free_gb: 167,
  disk_percent: 34.8,
  uptime: '42d 7h 23m',
  load_avg: '0.45 0.62 0.71',
  hostname: 'vps-prod-01',
};

// --- Applications ---
export const mockApplications: Application[] = [
  {
    id: 'app-1',
    name: 'api-gateway',
    runtime: 'nodejs',
    version: '20.11.0',
    status: 'running',
    domain: 'api.lightpanel.dev',
    port: 3001,
    cpu_usage: 12.3,
    memory_usage: 256,
    memory_limit: 512,
    last_deployment: '2026-08-03T14:22:00Z',
    git_repo: 'github.com/lightpanel/api-gateway',
    git_branch: 'main',
    build_command: 'npm run build',
    start_command: 'npm start',
    env_vars: { NODE_ENV: 'production', PORT: '3001' },
    created_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'app-2',
    name: 'web-dashboard',
    runtime: 'nextjs',
    version: '14.2.0',
    status: 'running',
    domain: 'app.lightpanel.dev',
    port: 3000,
    cpu_usage: 8.1,
    memory_usage: 384,
    memory_limit: 1024,
    last_deployment: '2026-08-04T09:15:00Z',
    git_repo: 'github.com/lightpanel/dashboard',
    git_branch: 'main',
    build_command: 'npm run build',
    start_command: 'npm start',
    env_vars: { NODE_ENV: 'production', NEXT_PUBLIC_API_URL: 'https://api.lightpanel.dev' },
    created_at: '2026-06-20T14:30:00Z',
  },
  {
    id: 'app-3',
    name: 'blog-backend',
    runtime: 'python',
    version: '3.12.0',
    status: 'running',
    domain: 'blog-api.lightpanel.dev',
    port: 8000,
    cpu_usage: 3.2,
    memory_usage: 128,
    memory_limit: 256,
    last_deployment: '2026-07-28T16:45:00Z',
    git_repo: 'github.com/lightpanel/blog-api',
    git_branch: 'production',
    build_command: 'pip install -r requirements.txt',
    start_command: 'uvicorn main:app --host 0.0.0.0 --port 8000',
    env_vars: { PYTHONPATH: '/app', DATABASE_URL: 'postgresql://...' },
    created_at: '2026-07-01T09:00:00Z',
  },
  {
    id: 'app-4',
    name: 'auth-service',
    runtime: 'java',
    version: '21.0.1',
    status: 'stopped',
    domain: 'auth.lightpanel.dev',
    port: 8080,
    cpu_usage: 0,
    memory_usage: 0,
    memory_limit: 768,
    last_deployment: '2026-07-15T11:30:00Z',
    git_repo: 'github.com/lightpanel/auth-service',
    git_branch: 'main',
    build_command: './gradlew build',
    start_command: 'java -jar build/libs/auth-0.1.0.jar',
    env_vars: { SPRING_PROFILES_ACTIVE: 'production' },
    created_at: '2026-07-10T08:00:00Z',
  },
  {
    id: 'app-5',
    name: 'payment-processor',
    runtime: 'dotnet',
    version: '8.0.0',
    status: 'running',
    domain: 'payments.lightpanel.dev',
    port: 5000,
    cpu_usage: 5.7,
    memory_usage: 192,
    memory_limit: 512,
    last_deployment: '2026-08-01T18:00:00Z',
    git_repo: 'github.com/lightpanel/payments',
    git_branch: 'release',
    build_command: 'dotnet publish -c Release',
    start_command: 'dotnet PaymentProcessor.dll',
    env_vars: { ASPNETCORE_ENVIRONMENT: 'Production' },
    created_at: '2026-07-20T12:00:00Z',
  },
];

// --- Websites ---
export const mockWebsites: Website[] = [
  {
    id: 'site-1',
    name: 'lightpanel.dev',
    domain: 'lightpanel.dev',
    document_root: '/var/www/lightpanel.dev',
    runtime: 'static',
    ssl_enabled: true,
    ssl_status: 'active',
    deployment_status: 'success',
    traffic_today: 2847,
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'site-2',
    name: 'docs.lightpanel.dev',
    domain: 'docs.lightpanel.dev',
    document_root: '/var/www/docs.lightpanel.dev',
    runtime: 'static',
    ssl_enabled: true,
    ssl_status: 'active',
    deployment_status: 'success',
    traffic_today: 1523,
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'site-3',
    name: 'portfolio.example.com',
    domain: 'portfolio.example.com',
    document_root: '/var/www/portfolio.example.com',
    runtime: 'php',
    php_version: '8.3',
    ssl_enabled: true,
    ssl_status: 'active',
    deployment_status: 'success',
    traffic_today: 456,
    created_at: '2026-07-15T14:00:00Z',
  },
  {
    id: 'site-4',
    name: 'staging.lightpanel.dev',
    domain: 'staging.lightpanel.dev',
    document_root: '/var/www/staging.lightpanel.dev',
    runtime: 'php',
    php_version: '8.2',
    ssl_enabled: false,
    ssl_status: 'none',
    deployment_status: 'deploying',
    traffic_today: 89,
    created_at: '2026-08-01T16:00:00Z',
  },
];

// --- Domains ---
export const mockDomains: Domain[] = [
  {
    id: 'dom-1',
    name: 'lightpanel.dev',
    status: 'active',
    dns_status: 'propagated',
    ssl_status: 'active',
    linked_to: 'lightpanel.dev',
    linked_type: 'website',
    nameservers: ['ns1.digitalocean.com', 'ns2.digitalocean.com', 'ns3.digitalocean.com'],
    verified: true,
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'dom-2',
    name: 'example.com',
    status: 'active',
    dns_status: 'propagated',
    ssl_status: 'active',
    linked_to: 'portfolio.example.com',
    linked_type: 'website',
    nameservers: ['ns1.cloudflare.com', 'ns2.cloudflare.com'],
    verified: true,
    created_at: '2026-06-20T12:00:00Z',
  },
  {
    id: 'dom-3',
    name: 'myproject.io',
    status: 'pending',
    dns_status: 'pending',
    ssl_status: 'none',
    nameservers: [],
    verified: false,
    created_at: '2026-08-03T10:00:00Z',
  },
];

// --- Subdomains ---
export const mockSubdomains: Subdomain[] = [
  {
    id: 'sub-1',
    name: 'api',
    parent_domain: 'lightpanel.dev',
    full_domain: 'api.lightpanel.dev',
    target: 'api-gateway',
    target_type: 'application',
    port: 3001,
    ssl_enabled: true,
    created_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'sub-2',
    name: 'app',
    parent_domain: 'lightpanel.dev',
    full_domain: 'app.lightpanel.dev',
    target: 'web-dashboard',
    target_type: 'application',
    port: 3000,
    ssl_enabled: true,
    created_at: '2026-06-20T14:30:00Z',
  },
  {
    id: 'sub-3',
    name: 'docs',
    parent_domain: 'lightpanel.dev',
    full_domain: 'docs.lightpanel.dev',
    target: 'docs.lightpanel.dev',
    target_type: 'website',
    ssl_enabled: true,
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'sub-4',
    name: 'staging',
    parent_domain: 'lightpanel.dev',
    full_domain: 'staging.lightpanel.dev',
    target: 'staging.lightpanel.dev',
    target_type: 'website',
    ssl_enabled: false,
    created_at: '2026-08-01T16:00:00Z',
  },
  {
    id: 'sub-5',
    name: 'blog-api',
    parent_domain: 'lightpanel.dev',
    full_domain: 'blog-api.lightpanel.dev',
    target: 'blog-backend',
    target_type: 'application',
    port: 8000,
    ssl_enabled: true,
    created_at: '2026-07-01T09:00:00Z',
  },
];

// --- Databases ---
export const mockDatabases: DatabaseExtended[] = [
  {
    id: 'db-1',
    name: 'lightpanel_prod',
    type: 'postgresql',
    version: '16.1',
    status: 'running',
    host: '127.0.0.1',
    port: 5432,
    storage_used_mb: 1240,
    storage_limit_mb: 5120,
    linked_apps: ['api-gateway', 'web-dashboard'],
    last_backup: '2026-08-04T02:00:00Z',
    username: 'lightpanel_user',
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'db-2',
    name: 'blog_db',
    type: 'postgresql',
    version: '16.1',
    status: 'running',
    host: '127.0.0.1',
    port: 5432,
    storage_used_mb: 340,
    storage_limit_mb: 2048,
    linked_apps: ['blog-backend'],
    last_backup: '2026-08-04T02:00:00Z',
    username: 'blog_user',
    created_at: '2026-07-01T09:00:00Z',
  },
  {
    id: 'db-3',
    name: 'cache_store',
    type: 'redis',
    version: '7.2.4',
    status: 'running',
    host: '127.0.0.1',
    port: 6379,
    storage_used_mb: 64,
    storage_limit_mb: 512,
    linked_apps: ['api-gateway', 'auth-service'],
    username: 'default',
    created_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'db-4',
    name: 'analytics_db',
    type: 'mongodb',
    version: '7.0.4',
    status: 'running',
    host: '127.0.0.1',
    port: 27017,
    storage_used_mb: 2800,
    storage_limit_mb: 10240,
    linked_apps: ['web-dashboard'],
    last_backup: '2026-08-03T02:00:00Z',
    username: 'analytics_admin',
    created_at: '2026-06-20T14:30:00Z',
  },
  {
    id: 'db-5',
    name: 'wordpress_db',
    type: 'mariadb',
    version: '11.2.2',
    status: 'stopped',
    host: '127.0.0.1',
    port: 3306,
    storage_used_mb: 156,
    storage_limit_mb: 1024,
    linked_apps: [],
    last_backup: '2026-07-28T02:00:00Z',
    username: 'wp_user',
    created_at: '2026-07-15T14:00:00Z',
  },
];

// --- SSL Certificates ---
export const mockSSLCertificates: SSLCertificate[] = [
  {
    id: 'ssl-1',
    domain: 'lightpanel.dev',
    alt_names: ['*.lightpanel.dev'],
    issuer: "Let's Encrypt",
    status: 'active',
    issued_at: '2026-07-05T00:00:00Z',
    expires_at: '2026-10-03T00:00:00Z',
    auto_renew: true,
    challenge_type: 'dns-01',
  },
  {
    id: 'ssl-2',
    domain: 'example.com',
    alt_names: ['www.example.com'],
    issuer: "Let's Encrypt",
    status: 'active',
    issued_at: '2026-06-20T00:00:00Z',
    expires_at: '2026-09-18T00:00:00Z',
    auto_renew: true,
    challenge_type: 'http-01',
  },
  {
    id: 'ssl-3',
    domain: 'api.lightpanel.dev',
    alt_names: [],
    issuer: "Let's Encrypt",
    status: 'expiring',
    issued_at: '2026-05-10T00:00:00Z',
    expires_at: '2026-08-08T00:00:00Z',
    auto_renew: true,
    challenge_type: 'http-01',
  },
];

// --- Deployments ---
export const mockDeployments: Deployment[] = [
  {
    id: 'dep-1',
    app_name: 'web-dashboard',
    git_repo: 'github.com/lightpanel/dashboard',
    branch: 'main',
    commit: 'a1b2c3d',
    commit_message: 'feat: add monitoring charts to dashboard',
    status: 'success',
    duration: 127,
    started_at: '2026-08-04T09:13:00Z',
    finished_at: '2026-08-04T09:15:07Z',
    triggered_by: 'admin',
  },
  {
    id: 'dep-2',
    app_name: 'api-gateway',
    git_repo: 'github.com/lightpanel/api-gateway',
    branch: 'main',
    commit: 'e4f5g6h',
    commit_message: 'fix: resolve rate limiting edge case',
    status: 'success',
    duration: 89,
    started_at: '2026-08-03T14:20:31Z',
    finished_at: '2026-08-03T14:22:00Z',
    triggered_by: 'admin',
  },
  {
    id: 'dep-3',
    app_name: 'blog-backend',
    git_repo: 'github.com/lightpanel/blog-api',
    branch: 'production',
    commit: 'i7j8k9l',
    commit_message: 'chore: update dependencies',
    status: 'failed',
    duration: 45,
    started_at: '2026-08-02T10:00:00Z',
    finished_at: '2026-08-02T10:00:45Z',
    triggered_by: 'admin',
  },
  {
    id: 'dep-4',
    app_name: 'payment-processor',
    git_repo: 'github.com/lightpanel/payments',
    branch: 'release',
    commit: 'm0n1o2p',
    commit_message: 'feat: add webhook retry logic',
    status: 'success',
    duration: 203,
    started_at: '2026-08-01T17:56:37Z',
    finished_at: '2026-08-01T18:00:00Z',
    triggered_by: 'admin',
  },
  {
    id: 'dep-5',
    app_name: 'web-dashboard',
    git_repo: 'github.com/lightpanel/dashboard',
    branch: 'main',
    commit: 'q3r4s5t',
    commit_message: 'refactor: improve sidebar navigation',
    status: 'success',
    duration: 134,
    started_at: '2026-07-31T11:20:00Z',
    finished_at: '2026-07-31T11:22:14Z',
    triggered_by: 'admin',
  },
];

// --- Backups ---
export const mockBackups: Backup[] = [
  {
    id: 'bak-1',
    name: 'lightpanel_prod_daily',
    type: 'database',
    target_name: 'lightpanel_prod',
    status: 'completed',
    size_mb: 245,
    created_at: '2026-08-04T02:00:00Z',
    retention_days: 30,
    storage_location: '/backups/databases',
    scheduled: true,
  },
  {
    id: 'bak-2',
    name: 'lightpanel.dev_full',
    type: 'website',
    target_name: 'lightpanel.dev',
    status: 'completed',
    size_mb: 1820,
    created_at: '2026-08-03T03:00:00Z',
    retention_days: 14,
    storage_location: '/backups/websites',
    scheduled: true,
  },
  {
    id: 'bak-3',
    name: 'api-gateway_manual',
    type: 'application',
    target_name: 'api-gateway',
    status: 'completed',
    size_mb: 89,
    created_at: '2026-08-02T16:30:00Z',
    retention_days: 7,
    storage_location: '/backups/applications',
    scheduled: false,
  },
  {
    id: 'bak-4',
    name: 'full_server_weekly',
    type: 'full',
    target_name: 'vps-prod-01',
    status: 'in_progress',
    size_mb: 0,
    created_at: '2026-08-04T04:00:00Z',
    retention_days: 60,
    storage_location: '/backups/full',
    scheduled: true,
  },
];

// --- Cron Jobs ---
export const mockCronJobs: CronJob[] = [
  {
    id: 'cron-1',
    name: 'Database Backup',
    command: '/opt/lightpanel/scripts/backup-db.sh',
    schedule: '0 2 * * *',
    status: 'active',
    last_run: '2026-08-04T02:00:00Z',
    next_run: '2026-08-05T02:00:00Z',
    last_status: 'success',
  },
  {
    id: 'cron-2',
    name: 'SSL Renewal Check',
    command: 'certbot renew --quiet',
    schedule: '0 0 */3 * *',
    status: 'active',
    last_run: '2026-08-03T00:00:00Z',
    next_run: '2026-08-06T00:00:00Z',
    last_status: 'success',
  },
  {
    id: 'cron-3',
    name: 'Log Rotation',
    command: 'logrotate /etc/logrotate.d/lightpanel',
    schedule: '0 0 * * 0',
    status: 'active',
    last_run: '2026-08-04T00:00:00Z',
    next_run: '2026-08-11T00:00:00Z',
    last_status: 'success',
  },
  {
    id: 'cron-4',
    name: 'System Health Report',
    command: '/opt/lightpanel/scripts/health-report.sh',
    schedule: '*/30 * * * *',
    status: 'paused',
    last_run: '2026-08-01T12:00:00Z',
    last_status: 'failed',
  },
];

// --- Log Entries ---
export const mockLogs: LogEntry[] = [
  { id: 'log-1', timestamp: '2026-08-04T11:22:04Z', level: 'info', source: 'nginx', message: 'GET /api/stats 200 12ms - api.lightpanel.dev' },
  { id: 'log-2', timestamp: '2026-08-04T11:21:58Z', level: 'info', source: 'nginx', message: 'GET / 200 3ms - lightpanel.dev' },
  { id: 'log-3', timestamp: '2026-08-04T11:21:45Z', level: 'warn', source: 'ssl', message: 'Certificate for api.lightpanel.dev expires in 4 days' },
  { id: 'log-4', timestamp: '2026-08-04T11:21:30Z', level: 'info', source: 'deployment', message: 'Deployment dep-1 completed successfully for web-dashboard' },
  { id: 'log-5', timestamp: '2026-08-04T11:21:12Z', level: 'error', source: 'application', message: 'auth-service: Connection refused on port 8080' },
  { id: 'log-6', timestamp: '2026-08-04T11:20:55Z', level: 'info', source: 'database', message: 'Backup completed for lightpanel_prod (245 MB)' },
  { id: 'log-7', timestamp: '2026-08-04T11:20:30Z', level: 'debug', source: 'monitor', message: 'CPU sample: 23.4% | Memory: 3276/8192 MB | Disk: 89/256 GB' },
  { id: 'log-8', timestamp: '2026-08-04T11:20:00Z', level: 'info', source: 'system', message: 'Cron job "Database Backup" executed successfully' },
  { id: 'log-9', timestamp: '2026-08-04T11:19:45Z', level: 'warn', source: 'nginx', message: 'Upstream timeout for blog-api.lightpanel.dev (>5s)' },
  { id: 'log-10', timestamp: '2026-08-04T11:19:30Z', level: 'info', source: 'ssl', message: 'Certificate renewed for example.com' },
  { id: 'log-11', timestamp: '2026-08-04T11:19:00Z', level: 'error', source: 'deployment', message: 'Build failed for blog-backend: ModuleNotFoundError: No module named "fastapi"' },
  { id: 'log-12', timestamp: '2026-08-04T11:18:30Z', level: 'info', source: 'system', message: 'nginx configuration test passed' },
];

// --- Notifications ---
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'warning',
    title: 'SSL Certificate Expiring',
    message: 'Certificate for api.lightpanel.dev expires in 4 days.',
    read: false,
    created_at: '2026-08-04T11:21:45Z',
    action_url: '/ssl',
  },
  {
    id: 'notif-2',
    type: 'success',
    title: 'Deployment Successful',
    message: 'web-dashboard deployed successfully from main@a1b2c3d.',
    read: false,
    created_at: '2026-08-04T09:15:07Z',
    action_url: '/deployments',
  },
  {
    id: 'notif-3',
    type: 'error',
    title: 'Application Down',
    message: 'auth-service is not responding on port 8080.',
    read: false,
    created_at: '2026-08-04T11:21:12Z',
    action_url: '/applications',
  },
  {
    id: 'notif-4',
    type: 'info',
    title: 'Backup Completed',
    message: 'Daily backup of lightpanel_prod completed (245 MB).',
    read: true,
    created_at: '2026-08-04T02:00:30Z',
    action_url: '/backups',
  },
  {
    id: 'notif-5',
    type: 'error',
    title: 'Build Failed',
    message: 'blog-backend deployment failed: missing dependency.',
    read: true,
    created_at: '2026-08-02T10:00:45Z',
    action_url: '/deployments',
  },
];

// --- Activity Events ---
export const mockActivity: ActivityEvent[] = [
  { id: 'act-1', type: 'deployment', title: 'Deployed web-dashboard', description: 'main@a1b2c3d • 2m 7s', timestamp: '2026-08-04T09:15:07Z', user: 'admin' },
  { id: 'act-2', type: 'ssl', title: 'SSL renewed for example.com', description: "Let's Encrypt • auto-renew", timestamp: '2026-08-04T11:19:30Z', user: 'system' },
  { id: 'act-3', type: 'backup', title: 'Database backup completed', description: 'lightpanel_prod • 245 MB', timestamp: '2026-08-04T02:00:30Z', user: 'system' },
  { id: 'act-4', type: 'deployment', title: 'Deployed api-gateway', description: 'main@e4f5g6h • 1m 29s', timestamp: '2026-08-03T14:22:00Z', user: 'admin' },
  { id: 'act-5', type: 'site', title: 'Created staging.lightpanel.dev', description: 'PHP 8.2 • /var/www/staging', timestamp: '2026-08-01T16:00:00Z', user: 'admin' },
  { id: 'act-6', type: 'database', title: 'Created analytics_db', description: 'MongoDB 7.0.4 • port 27017', timestamp: '2026-06-20T14:30:00Z', user: 'admin' },
  { id: 'act-7', type: 'error', title: 'Build failed for blog-backend', description: 'ModuleNotFoundError', timestamp: '2026-08-02T10:00:45Z', user: 'system' },
  { id: 'act-8', type: 'deployment', title: 'Deployed payment-processor', description: 'release@m0n1o2p • 3m 23s', timestamp: '2026-08-01T18:00:00Z', user: 'admin' },
];

// --- File Manager ---
export const mockFiles: FileItem[] = [
  { name: 'public_html', path: '/var/www/lightpanel.dev/public_html', type: 'directory', size: 0, modified: '2026-08-04T09:15:07Z', permissions: 'drwxr-xr-x' },
  { name: 'logs', path: '/var/www/lightpanel.dev/logs', type: 'directory', size: 0, modified: '2026-08-04T11:22:04Z', permissions: 'drwxr-x---' },
  { name: 'config', path: '/var/www/lightpanel.dev/config', type: 'directory', size: 0, modified: '2026-08-03T14:22:00Z', permissions: 'drwxr-xr-x' },
  { name: '.env', path: '/var/www/lightpanel.dev/.env', type: 'file', size: 1247, modified: '2026-08-01T16:00:00Z', permissions: '-rw-------', extension: 'env' },
  { name: 'index.html', path: '/var/www/lightpanel.dev/index.html', type: 'file', size: 4523, modified: '2026-08-04T09:15:07Z', permissions: '-rw-r--r--', extension: 'html' },
  { name: 'package.json', path: '/var/www/lightpanel.dev/package.json', type: 'file', size: 892, modified: '2026-08-03T14:22:00Z', permissions: '-rw-r--r--', extension: 'json' },
  { name: 'server.js', path: '/var/www/lightpanel.dev/server.js', type: 'file', size: 3156, modified: '2026-08-02T10:00:00Z', permissions: '-rw-r--r--', extension: 'js' },
  { name: 'README.md', path: '/var/www/lightpanel.dev/README.md', type: 'file', size: 2834, modified: '2026-07-28T16:45:00Z', permissions: '-rw-r--r--', extension: 'md' },
  { name: 'docker-compose.yml', path: '/var/www/lightpanel.dev/docker-compose.yml', type: 'file', size: 1567, modified: '2026-07-15T11:30:00Z', permissions: '-rw-r--r--', extension: 'yml' },
  { name: 'nginx.conf', path: '/var/www/lightpanel.dev/nginx.conf', type: 'file', size: 723, modified: '2026-07-10T08:00:00Z', permissions: '-rw-r--r--', extension: 'conf' },
];

// --- Monitoring Time Series ---
export function generateTimeSeriesData(hours: number, baseValue: number, variance: number): MonitoringDataPoint[] {
  const points: MonitoringDataPoint[] = [];
  const now = Date.now();
  const interval = (hours * 3600 * 1000) / 60; // ~60 data points
  for (let i = 59; i >= 0; i--) {
    const timestamp = new Date(now - i * interval).toISOString();
    const value = Math.max(0, Math.min(100, baseValue + (Math.random() - 0.5) * variance * 2));
    points.push({ timestamp, value: Math.round(value * 10) / 10 });
  }
  return points;
}

// --- Environment Variables ---
export const mockEnvVariables: EnvVariable[] = [
  { key: 'NODE_ENV', value: 'production', target: 'api-gateway', type: 'plain' },
  { key: 'PORT', value: '3001', target: 'api-gateway', type: 'plain' },
  { key: 'DATABASE_URL', value: '••••••••••••••••', target: 'api-gateway', type: 'secret' },
  { key: 'JWT_SECRET', value: '••••••••••••••••', target: 'api-gateway', type: 'secret' },
  { key: 'REDIS_URL', value: 'redis://127.0.0.1:6379', target: 'api-gateway', type: 'plain' },
  { key: 'NEXT_PUBLIC_API_URL', value: 'https://api.lightpanel.dev', target: 'web-dashboard', type: 'plain' },
  { key: 'PYTHONPATH', value: '/app', target: 'blog-backend', type: 'plain' },
];

// --- EMAIL MODULE MOCK DATA ---

export const mockEmailDomains: EmailDomain[] = [
  {
    id: 'edom-1',
    name: 'lightpanel.dev',
    mailboxes_count: 5,
    aliases_count: 8,
    catchall_address: 'admin@lightpanel.dev',
    dkim_status: 'valid',
    spf_status: 'valid',
    dmarc_status: 'valid',
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'edom-2',
    name: 'example.com',
    mailboxes_count: 2,
    aliases_count: 3,
    dkim_status: 'valid',
    spf_status: 'valid',
    dmarc_status: 'pending',
    created_at: '2026-06-20T12:00:00Z',
  },
  {
    id: 'edom-3',
    name: 'myproject.io',
    mailboxes_count: 1,
    aliases_count: 0,
    dkim_status: 'missing',
    spf_status: 'pending',
    dmarc_status: 'missing',
    created_at: '2026-08-03T10:00:00Z',
  },
];

export const mockMailboxes: Mailbox[] = [
  {
    id: 'mbox-1',
    email: 'admin@lightpanel.dev',
    domain: 'lightpanel.dev',
    quota_mb: 5120,
    used_mb: 840,
    status: 'active',
    imap_enabled: true,
    smtp_enabled: true,
    pop3_enabled: true,
    auto_reply_enabled: false,
    aliases: ['root@lightpanel.dev', 'postmaster@lightpanel.dev', 'sysadmin@lightpanel.dev'],
    created_at: '2026-05-10T08:00:00Z',
    last_login: '2026-08-04T18:45:00Z',
  },
  {
    id: 'mbox-2',
    email: 'support@lightpanel.dev',
    domain: 'lightpanel.dev',
    quota_mb: 10240,
    used_mb: 3420,
    status: 'active',
    imap_enabled: true,
    smtp_enabled: true,
    pop3_enabled: false,
    auto_reply_enabled: true,
    auto_reply_subject: 'Thank you for contacting LightPanel Support',
    auto_reply_body: 'We have received your ticket and will respond within 2 hours.',
    aliases: ['help@lightpanel.dev', 'tickets@lightpanel.dev'],
    created_at: '2026-05-12T10:00:00Z',
    last_login: '2026-08-04T16:12:00Z',
  },
  {
    id: 'mbox-3',
    email: 'alex@lightpanel.dev',
    domain: 'lightpanel.dev',
    quota_mb: 2048,
    used_mb: 412,
    status: 'active',
    imap_enabled: true,
    smtp_enabled: true,
    pop3_enabled: true,
    auto_reply_enabled: false,
    forward_address: 'alex.personal@gmail.com',
    aliases: ['alex.dev@lightpanel.dev'],
    created_at: '2026-06-01T09:00:00Z',
    last_login: '2026-08-04T12:30:00Z',
  },
  {
    id: 'mbox-4',
    email: 'contact@example.com',
    domain: 'example.com',
    quota_mb: 1024,
    used_mb: 156,
    status: 'active',
    imap_enabled: true,
    smtp_enabled: true,
    pop3_enabled: true,
    auto_reply_enabled: false,
    aliases: ['info@example.com'],
    created_at: '2026-06-20T12:00:00Z',
    last_login: '2026-08-03T15:20:00Z',
  },
  {
    id: 'mbox-5',
    email: 'security-alerts@lightpanel.dev',
    domain: 'lightpanel.dev',
    quota_mb: 2048,
    used_mb: 95,
    status: 'active',
    imap_enabled: true,
    smtp_enabled: true,
    pop3_enabled: false,
    auto_reply_enabled: false,
    aliases: ['abuse@lightpanel.dev', 'security@lightpanel.dev'],
    created_at: '2026-07-05T14:00:00Z',
    last_login: '2026-08-04T19:01:00Z',
  },
];

export const mockEmailAliases: EmailAlias[] = [
  {
    id: 'alias-1',
    alias_email: 'sales@lightpanel.dev',
    target_emails: ['alex@lightpanel.dev', 'support@lightpanel.dev'],
    domain: 'lightpanel.dev',
    type: 'group',
    created_at: '2026-05-15T10:00:00Z',
  },
  {
    id: 'alias-2',
    alias_email: 'hello@example.com',
    target_emails: ['contact@example.com'],
    domain: 'example.com',
    type: 'alias',
    created_at: '2026-06-20T14:00:00Z',
  },
  {
    id: 'alias-3',
    alias_email: '*@lightpanel.dev',
    target_emails: ['admin@lightpanel.dev'],
    domain: 'lightpanel.dev',
    type: 'catch-all',
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'alias-4',
    alias_email: 'billing@lightpanel.dev',
    target_emails: ['admin@lightpanel.dev'],
    domain: 'lightpanel.dev',
    type: 'forwarder',
    created_at: '2026-06-01T11:00:00Z',
  },
];

export const mockSpamSettings: SpamSettings = {
  domain: 'lightpanel.dev',
  spam_score_threshold: 5.0,
  greylisting: true,
  bayesian_filtering: true,
  auto_delete_spam: false,
  blacklist: ['spammer.com', 'bad-domain.net', '198.51.100.42'],
  whitelist: ['trusted-partner.com', 'sendgrid.me'],
};

export const mockDNSAuthRecords: DNSAuthRecord[] = [
  {
    type: 'MX',
    host: '@',
    value: '10 mail.lightpanel.dev',
    status: 'valid',
    instructions: 'Points incoming email to your server mail transfer agent.',
  },
  {
    type: 'A (Mail)',
    host: 'mail',
    value: '192.0.2.1',
    status: 'valid',
    instructions: 'A record pointing mail.lightpanel.dev to your server IP address.',
  },
  {
    type: 'TXT (SPF)',
    host: '@',
    value: 'v=spf1 mx a ip4:192.0.2.1 ~all',
    status: 'valid',
    instructions: 'Authorizes your server IP to send email on behalf of your domain.',
  },
  {
    type: 'TXT (DKIM)',
    host: 'default._domainkey',
    value: 'v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQ...',
    status: 'valid',
    instructions: 'Cryptographically signs outbound mail to prevent spoofing.',
  },
  {
    type: 'TXT (DMARC)',
    host: '_dmarc',
    value: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@lightpanel.dev',
    status: 'valid',
    instructions: 'Defines enforcement policy for SPF and DKIM failures.',
  },
];

export const mockWebmailMessages: MailMessage[] = [
  {
    id: 'msg-1',
    folder: 'inbox',
    from: 'GitHub Notifications <notifications@github.com>',
    to: 'admin@lightpanel.dev',
    subject: '[LightPanel/core] Release v2.4.0 is now available',
    snippet: 'Release v2.4.0 includes performance improvements for Nginx config reloading and Certbot automation...',
    body: `Hello Admin,\n\nRelease v2.4.0 for LightPanel/core has been officially published.\n\nHighlights:\n- Faster Nginx profile reload\n- DKIM key generation improvements\n- Redis 7.2 support\n\nBest,\nThe LightPanel Team`,
    timestamp: '2026-08-04T18:30:00Z',
    read: false,
    flagged: true,
    attachments: [
      { name: 'release-notes-v2.4.0.pdf', size: 245000, type: 'application/pdf' },
    ],
  },
  {
    id: 'msg-2',
    folder: 'inbox',
    from: 'Let\'s Encrypt <expiry@letsencrypt.org>',
    to: 'admin@lightpanel.dev',
    subject: 'Certificate renewal notice for api.lightpanel.dev',
    snippet: 'Your certificate for api.lightpanel.dev will expire in 4 days. Automatic renewal is scheduled...',
    body: `Dear Customer,\n\nYour Let's Encrypt certificate for api.lightpanel.dev expires on 2026-08-08.\n\nAutomatic renewal is enabled via Certbot. No action is required.`,
    timestamp: '2026-08-04T14:15:00Z',
    read: true,
    flagged: false,
  },
  {
    id: 'msg-3',
    folder: 'sent',
    from: 'admin@lightpanel.dev',
    to: 'support@digitalocean.com',
    subject: 'PTR Record Request for 192.0.2.1',
    snippet: 'Please configure the reverse DNS (PTR) record for IP 192.0.2.1 to mail.lightpanel.dev...',
    body: `Hi Support,\n\nPlease update the PTR record for our IPv4 address 192.0.2.1 to mail.lightpanel.dev for outbound SMTP compliance.\n\nThank you,\nSystem Administrator`,
    timestamp: '2026-08-03T11:00:00Z',
    read: true,
    flagged: false,
  },
  {
    id: 'msg-4',
    folder: 'drafts',
    from: 'admin@lightpanel.dev',
    to: 'team@lightpanel.dev',
    subject: 'Quarterly Server Maintenance Notice',
    snippet: 'Draft: We will be performing scheduled kernel updates on Sunday at 02:00 UTC...',
    body: `Team,\n\nPlease note scheduled kernel maintenance for vps-prod-01 on Sunday at 02:00 UTC. Expected downtime: < 3 mins.`,
    timestamp: '2026-08-04T09:00:00Z',
    read: true,
    flagged: false,
  },
  {
    id: 'msg-5',
    folder: 'spam',
    from: 'Claim Reward <no-reply@win-prizes-fast.net>',
    to: 'admin@lightpanel.dev',
    subject: 'CRITICAL: You have 1 pending reward claim!',
    snippet: 'Click here immediately to claim your $1,000 server hosting credit...',
    body: `You have won a free prize! Click the link below to verify your account.`,
    timestamp: '2026-08-04T07:22:00Z',
    read: false,
    flagged: false,
  },
  {
    id: 'msg-6',
    folder: 'archive',
    from: 'Cloudflare <no-reply@notify.cloudflare.com>',
    to: 'admin@lightpanel.dev',
    subject: 'DNS Records updated for lightpanel.dev',
    snippet: 'MX and SPF records were successfully updated via API key lp_live_9f8a...',
    body: `Cloudflare DNS update confirmation: MX mail.lightpanel.dev priority 10 added.`,
    timestamp: '2026-07-28T16:00:00Z',
    read: true,
    flagged: false,
  },
];

export const mockMailLogs: MailLog[] = [
  { id: 'mlog-1', timestamp: '2026-08-04T19:12:00Z', sender: 'notifications@github.com', recipient: 'admin@lightpanel.dev', subject: '[LightPanel/core] Release v2.4.0', status: 'delivered', spam_score: 0.1, client_ip: '140.82.115.1' },
  { id: 'mlog-2', timestamp: '2026-08-04T18:45:00Z', sender: 'admin@lightpanel.dev', recipient: 'alex.personal@gmail.com', subject: 'Fwd: System Alert', status: 'delivered', spam_score: 0.0, client_ip: '127.0.0.1' },
  { id: 'mlog-3', timestamp: '2026-08-04T17:30:00Z', sender: 'spammer@bad-domain.net', recipient: 'info@example.com', subject: 'Special Promotion Offer', status: 'rejected', spam_score: 8.7, client_ip: '198.51.100.42' },
  { id: 'mlog-4', timestamp: '2026-08-04T16:10:00Z', sender: 'user@external.com', recipient: 'support@lightpanel.dev', subject: 'Help with Nginx SSL', status: 'delivered', spam_score: 0.2, client_ip: '203.0.113.88' },
  { id: 'mlog-5', timestamp: '2026-08-04T15:00:00Z', sender: 'admin@lightpanel.dev', recipient: 'unreachable@broken-host.org', subject: 'Test Mail Delivery', status: 'bounced', spam_score: 0.0, client_ip: '127.0.0.1' },
];

export const mockQueueItems: QueueItem[] = [
  { id: 'q-1', queue_id: '4Wz9K10x8zZ1001', sender: 'admin@lightpanel.dev', recipient: 'digest-subscribers@example.com', size_bytes: 48200, arrived_at: '2026-08-04T19:20:00Z', status: 'active' },
  { id: 'q-2', queue_id: '4Wz8L92y7aA2002', sender: 'support@lightpanel.dev', recipient: 'user@slow-mx.org', size_bytes: 12400, arrived_at: '2026-08-04T18:50:00Z', status: 'deferred', delay_reason: 'Connection timed out to mx.slow-mx.org [45.33.22.11]:25' },
];
